"use client";

import { useEffect, useMemo, useState, useTransition } from 'react';
import { addDays, endOfMonth, format, startOfMonth, getDay } from 'date-fns';
import VariationSelector from './VariationSelector';
import { VariationStrategy, getStrategyDescription } from '@/app/lib/variationStrategies';

type Employee = { id: string; name: string; code: string | null };

type Assignment = { employee_id: string; date: string; symbol: string };

type MonthData = {
  month: { id: string; year: number; month: number };
  employees: Employee[];
  assignments: Assignment[];
  preview?: boolean;
  seed?: number;
  debug?: {
    coverageMorning: number;
    coverageEvening: number;
    totalEmployees: number;
    issues: number;
  };
};

// الجدول المعروض حالياً (في الذاكرة فقط - لا يُحفظ تلقائياً)
let currentDisplayedSchedule: {
  grid: Record<string, Record<string, string>>;
  seed: number;
} | null = null;

function toISO(y: number, m: number, d: number) {
  return format(new Date(y, m - 1, d), 'yyyy-MM-dd');
}

// أسماء الأشهر بالعربي
const MONTH_NAMES = [
  'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو',
  'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'
];

function getMonthName(m: number): string {
  return MONTH_NAMES[m - 1] || '';
}

export default function ScheduleGrid() {
  const [settings, setSettings] = useState<{ year?: number; month?: number }>({});
  const [data, setData] = useState<MonthData | null>(null);
  const [grid, setGrid] = useState<Record<string, Record<string, string>>>({}); // empId -> dateISO -> symbol (local edits only)
  const [gridOriginal, setGridOriginal] = useState<Record<string, Record<string, string>>>({}); // snapshot from server
  const [isPending, startTransition] = useTransition();
  const [msg, setMsg] = useState<string | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPreviewMode, setIsPreviewMode] = useState(true);
  const [showVariationSelector, setShowVariationSelector] = useState(false);
  const [usedSeeds, setUsedSeeds] = useState<Set<number>>(new Set());
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // load settings for year/month
  useEffect(() => {
    fetch('/api/settings').then((r) => r.json()).then((s) => setSettings({ year: s.year, month: s.month }));
  }, []);
  
  // ✨ AUTO GENERATION: توليد تلقائي عند فتح الصفحة
  useEffect(() => {
    if (!settings.year || !settings.month || hasAutoGenerated || isGenerating) return;
    
    // تأخير بسيط للتأكد من تحميل جميع البيانات
    const timer = setTimeout(() => {
      autoGenerateSchedule();
    }, 500);
    
    return () => clearTimeout(timer);
  }, [settings.year, settings.month, hasAutoGenerated, isGenerating]);

  const daysInMonth = useMemo(() => {
    if (!settings.year || !settings.month) return 0;
    const start = startOfMonth(new Date(settings.year, (settings.month || 1) - 1, 1));
    const end = endOfMonth(start);
    return Number(format(end, 'd'));
  }, [settings.year, settings.month]);

  // تحديث الـ grid من البيانات
  function updateGridFromData(json: MonthData) {
    setData(json);
    
    // لوج للتشخيص
    console.log('[UI] updateGridFromData - employees:', json.employees.length, json.employees.map(e => `${e.name}(${e.id})`));
    console.log('[UI] updateGridFromData - assignments:', json.assignments.length);
    
    const g: Record<string, Record<string, string>> = {};
    for (const emp of json.employees) {
      g[String(emp.id)] = {};  // تأكد من أنه string
    }
    for (const a of json.assignments) {
      const empId = String(a.employee_id);  // تأكد من أنه string
      if (!g[empId]) g[empId] = {};
      g[empId][a.date] = a.symbol;
    }
    setGrid(g);
    setGridOriginal(JSON.parse(JSON.stringify(g)));
  }

  // ✨ AUTO GENERATION: دالة التوليد التلقائي
  async function autoGenerateSchedule() {
    if (hasAutoGenerated) return;
    
    setIsGenerating(true);
    setMsg('🔄 جاري إنشاء جدول العمل تلقائياً...');
    
    try {
      // محاولة تحميل جدول محفوظ أولاً
      const savedRes = await fetch(`/api/schedule/${settings.year}/${settings.month}`);
      const savedJson = await savedRes.json();
      
      if (savedRes.ok && savedJson.assignments && savedJson.assignments.length > 0) {
        // يوجد جدول محفوظ - عرضه
        updateGridFromData(savedJson);
        setIsPreviewMode(false);
        setMsg('✅ تم تحميل الجدول المحفوظ');
        setHasAutoGenerated(true);
      } else {
        // لا يوجد جدول محفوظ - توليد جديد
        await generateNewScheduleWithVariation();
        setHasAutoGenerated(true);
      }
    } catch (error) {
      // في حالة الخطأ - توليد جدول جديد
      await generateNewScheduleWithVariation();
      setHasAutoGenerated(true);
    } finally {
      setIsGenerating(false);
    }
  }

  // 🔄 SMART REGENERATION: توليد جدول جديد مع variation strategy
  async function generateNewScheduleWithVariation(strategy?: VariationStrategy, offset?: number) {
    if (!settings.year || !settings.month) {
      setMsg('الرجاء تحديد السنة والشهر أولاً');
      return;
    }
    
    setIsGenerating(true);
    setMsg('جاري توليد جدول جديد...'); // رسالة مؤقتة أثناء التوليد فقط
    
    try {
      // ✅ seed عشوائي جديد كل مرة (غير مكرر)
      let newSeed = Date.now() + Math.floor(Math.random() * 1000000);
      
      // 🚫 منع التكرار: تأكد أن الـ seed جديد
      while (usedSeeds.has(newSeed)) {
        newSeed = Date.now() + Math.floor(Math.random() * 1000000);
      }
      setUsedSeeds(prev => new Set([...prev, newSeed]));
      
      // ═══════════════════════════════════════════════════════════════════
      // حساب هل هناك أسبوع مشترك في البداية أو النهاية
      // الأسبوع يبدأ السبت (6) وينتهي الخميس (4)، الجمعة (5) أوف
      // ═══════════════════════════════════════════════════════════════════
      const year = settings.year;
      const month = settings.month;
      const firstDayOfMonth = new Date(year, month - 1, 1);
      const lastDayOfMonth = new Date(year, month, 0);
      
      // هل الشهر يبدأ يوم السبت؟ إذا لا، فهناك أسبوع مشترك مع الشهر السابق
      const hasSharedWeekAtStart = firstDayOfMonth.getDay() !== 6; // 6 = السبت
      
      // هل الشهر ينتهي يوم الخميس أو الجمعة؟ إذا لا، فهناك أسبوع مشترك مع الشهر التالي
      const lastDayOfWeek = lastDayOfMonth.getDay();
      const hasSharedWeekAtEnd = lastDayOfWeek !== 4 && lastDayOfWeek !== 5; // 4=خميس, 5=جمعة
      
      console.log(`[generateNewSchedule] hasSharedWeekAtStart: ${hasSharedWeekAtStart}, hasSharedWeekAtEnd: ${hasSharedWeekAtEnd}`);
      
      // ═══════════════════════════════════════════════════════════════════
      // استخراج الشفتات من الجدول المعروض حاليًا (إذا كان موجودًا)
      // ═══════════════════════════════════════════════════════════════════
      let firstWeekShifts: Record<string, 'Morning' | 'Evening'> | undefined = undefined;
      let lastWeekShifts: Record<string, 'Morning' | 'Evening'> | undefined = undefined;
      
      if (data && data.assignments && data.assignments.length > 0) {
        const allDates = Array.from(new Set(data.assignments.map(a => a.date))).sort();
        
        // دالة مساعدة لاستخراج الشفت من الرمز
        const getShiftFromSymbol = (symbol: string): 'Morning' | 'Evening' | null => {
          const s = (symbol || '').toUpperCase();
          if (s.startsWith('M') || s === 'PT4') return 'Morning';
          if (s.startsWith('E') || s === 'PT5' || s === 'MA4') return 'Evening';
          return null;
        };
        
        // استخراج شفتات أول أسبوع (إذا كان هناك أسبوع مشترك في البداية)
        if (hasSharedWeekAtStart) {
          const firstWeekDates = allDates.slice(0, 7);
          firstWeekShifts = {};
          for (const emp of data.employees) {
            const empId = String(emp.id);
            for (const d of firstWeekDates) {
              const assignment = data.assignments.find(a => String(a.employee_id) === empId && a.date === d);
              if (!assignment) continue;
              const shift = getShiftFromSymbol(assignment.symbol);
              if (shift) {
                firstWeekShifts[empId] = shift;
                break;
              }
            }
          }
          console.log('[generateNewSchedule] Preserving first week shifts:', Object.keys(firstWeekShifts).length, 'employees');
        }
        
        // استخراج شفتات آخر أسبوع (إذا كان هناك أسبوع مشترك في النهاية)
        if (hasSharedWeekAtEnd) {
          const lastWeekDates = allDates.slice(-7);
          lastWeekShifts = {};
          for (const emp of data.employees) {
            const empId = String(emp.id);
            for (let i = lastWeekDates.length - 1; i >= 0; i--) {
              const d = lastWeekDates[i];
              const assignment = data.assignments.find(a => String(a.employee_id) === empId && a.date === d);
              if (!assignment) continue;
              const shift = getShiftFromSymbol(assignment.symbol);
              if (shift) {
                lastWeekShifts[empId] = shift;
                break;
              }
            }
          }
          console.log('[generateNewSchedule] Preserving last week shifts:', Object.keys(lastWeekShifts).length, 'employees');
        }
      }
      
      const res = await fetch('/api/schedule/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          year: settings.year, 
          month: settings.month,
          preview: true,
          seed: newSeed,
          variationStrategy: strategy,
          variationOffset: offset,
          firstWeekShifts,
          lastWeekShifts
        })
      });
      
      const json = await res.json();
      if (json.error) throw new Error(json.error);
      
      // دائماً اعرض الجدول بعد التوليد حتى لو ناقص أو فيه تحذير
      updateGridFromData(json);
      setIsPreviewMode(true);
      
      // ✅ حفظ الـ seed للاستخدام عند الحفظ
      currentDisplayedSchedule = {
        grid: JSON.parse(JSON.stringify(grid)),
        seed: json.seed || newSeed
      };
      
      if (!json.employees || json.employees.length === 0 || !json.assignments || json.assignments.length === 0) {
        setMsg('⚠️ تم التوليد لكن لا توجد بيانات كافية للجدول (راجع الإعدادات أو الموظفات)');
      } else {
        const strategyText = strategy ? ` (${getStrategyDescription(strategy)})` : '';
        setMsg(`✨ تم توليد جدول جديد بنجاح${strategyText}!`);
      }
    } catch (err: any) {
      setMsg('❌ خطأ: ' + (err.message || 'غير معروف'));
    } finally {
      setIsGenerating(false);
    }
  }

  // تحميل الجدول المحفوظ من DB
  function loadSavedSchedule() {
    if (!settings.year || !settings.month) return;
    startTransition(async () => {
      const res = await fetch(`/api/schedule/${settings.year}/${settings.month}`);
      const json = await res.json();
      if (!res.ok) { 
        setMsg(json.error || 'لا يوجد جدول محفوظ'); 
        return; 
      }
      updateGridFromData(json);
      setIsPreviewMode(false);
      setMsg('تم تحميل الجدول المحفوظ');
    });
  }

  // عند فتح الصفحة: لا تحميل تلقائي للجدول المحفوظ ولا توليد تلقائي
// المستخدم يختار بنفسه متى يولد أو يحمل المحفوظ

  // تحميل الجدول المحفوظ، وإذا لم يوجد يولد جدول جديد
  async function loadSavedScheduleOrGenerate() {
    if (!settings.year || !settings.month) return;
    
    try {
      const res = await fetch(`/api/schedule/${settings.year}/${settings.month}`);
      const json = await res.json();
      
      // إذا وجد جدول محفوظ وفيه بيانات
      if (res.ok && json.assignments && json.assignments.length > 0) {
        updateGridFromData(json);
        setIsPreviewMode(false);
        setMsg('تم تحميل الجدول المحفوظ');
      } else {
        // لا يوجد جدول محفوظ - عرض رسالة
        setMsg('لا يوجد جدول محفوظ - استخدم "توليد جدول جديد"');
      }
    } catch {
      // في حالة الخطأ - عرض رسالة
      setMsg('لا يوجد جدول محفوظ - استخدم "توليد جدول جديد"');
    }
  }

  // حفظ الجدول المعروض حالياً في DB (بدون تغيير أي شيء في الصفحة)
  async function saveCurrentScheduleToDb() {
    if (!settings.year || !settings.month) {
      setMsg('الرجاء تحديد السنة والشهر أولاً');
      return;
    }
    
    if (!data || Object.keys(grid).length === 0) {
      setMsg('❌ لا يوجد جدول للحفظ');
      return;
    }
    
    setIsGenerating(true);
    setMsg('جاري حفظ الجدول المعروض...');
    
    try {
      // تحويل الـ grid المعروض إلى قائمة changes
      const changes: { employee_id: string; date: string; symbol: string }[] = [];
      for (const empId of Object.keys(grid)) {
        const row = grid[empId] || {};
        for (const date of Object.keys(row)) {
          const symbol = (row[date] || '').toString().toUpperCase();
          changes.push({ employee_id: empId, date, symbol });
        }
      }
      
      if (changes.length === 0) {
        setMsg('❌ لا توجد بيانات للحفظ');
        return;
      }
      
      // حفظ الجدول المعروض مباشرة
      const res = await fetch('/api/schedule/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          year: settings.year, 
          month: settings.month,
          changes
        })
      });
      
      const json = await res.json();
      if (!res.ok || json.error) throw new Error(json.error || 'فشل الحفظ');
      
      // تحديث الحالة
      setIsPreviewMode(false);
      setGridOriginal(JSON.parse(JSON.stringify(grid)));
      
      setMsg(`✅ تم حفظ الجدول بنجاح (${changes.length} خلية)`);
    } catch (err: any) {
      setMsg('❌ خطأ في الحفظ: ' + (err.message || 'غير معروف'));
    } finally {
      setIsGenerating(false);
    }
  }

  // تصدير الجدول المعروض حالياً (وليس المحفوظ في DB أو الإعدادات)
  async function exportExcel() {
    // ✅ استخدام الشهر/السنة من الجدول المعروض (data) وليس من الإعدادات
    if (!data || !data.month) {
      setMsg('❌ لا يوجد جدول للتصدير');
      return;
    }
    if (Object.keys(grid).length === 0) {
      setMsg('❌ الجدول فارغ');
      return;
    }
    
    // استخدام الشهر والسنة من الجدول المعروض
    const displayedYear = data.month.year;
    const displayedMonth = data.month.month;
    
    setMsg(`جاري تصدير جدول ${getMonthName(displayedMonth)} ${displayedYear}...`);
    
    try {
      // تحويل الـ grid المعروض إلى assignments
      const assignments: Assignment[] = [];
      for (const empId of Object.keys(grid)) {
        for (const date of Object.keys(grid[empId] || {})) {
          const symbol = grid[empId][date];
          if (symbol) {
            assignments.push({ employee_id: empId, date, symbol });
          }
        }
      }
      
      // إرسال الجدول المعروض للتصدير (باستخدام الشهر/السنة من الجدول المعروض)
      const res = await fetch('/api/schedule/export-current', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          year: displayedYear,
          month: displayedMonth,
          employees: data.employees,
          assignments
        })
      });
      
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || 'فشل التصدير');
      }
      
      // تحميل الملف باسم الشهر المعروض
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `schedule_${displayedYear}_${String(displayedMonth).padStart(2, '0')}.xlsx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
      setMsg(`✅ تم تصدير جدول ${getMonthName(displayedMonth)} ${displayedYear} بنجاح`);
    } catch (err: any) {
      setMsg('❌ خطأ في التصدير: ' + (err.message || 'غير معروف'));
    }
  }

  async function importExcel(file: File) {
    try {
      setIsImporting(true);
      setMsg('جاري استيراد الملف...');
      const form = new FormData();
      form.append('file', file);
      form.append('autoGenerateNext', 'false');
      // ❌ لا نرسل السنة والشهر - نترك الـ API يستخرجها من الملف

      const res = await fetch('/api/schedule/import', {
        method: 'POST',
        body: form,
      });
      const json = await res.json();
      if (!res.ok || json.error) {
        setMsg('❌ ' + (json.error || 'فشل الاستيراد'));
        return;
      }
      
      // ✅ تحديث العرض بالشهر والسنة المستخرجة من الملف ثم عرض الرسالة بعد التأكد
      if (json.year && json.month) {
        setSettings({ year: json.year, month: json.month }); // تحديث settings فورًا
        const scheduleRes = await fetch(`/api/schedule/${json.year}/${json.month}`);
        const scheduleJson = await scheduleRes.json();
        if (scheduleRes.ok && scheduleJson.assignments) {
          setData(scheduleJson);
          updateGridFromData(scheduleJson);
          setIsPreviewMode(false);
          setMsg(`✅ تم استيراد جدول ${getMonthName(json.month)} ${json.year} بنجاح (${json.employees} موظفة، ${json.imported} خلية)`);
        } else {
          setMsg('❌ فشل في تحميل الجدول المستورد بعد الاستيراد');
        }
      }
    } catch (e: any) {
      setMsg('❌ ' + (e?.message || 'فشل الاستيراد'));
    } finally {
      setIsImporting(false);
    }
  }

  function saveChanges() {
    if (!settings.year || !settings.month) { setMsg('حدد السنة/الشهر أولاً'); return; }
    const changes: { employee_id: string; date: string; symbol: string }[] = [];
    for (const empId of Object.keys(grid)) {
      const row = grid[empId] || {};
      const base = gridOriginal[empId] || {};
      const dates = new Set([...Object.keys(row), ...Object.keys(base)]);
      for (const d of dates) {
        const v = (row[d] || '').toString().toUpperCase();
        const b = (base[d] || '').toString().toUpperCase();
        if (v !== b) {
          changes.push({ employee_id: empId, date: d, symbol: v });
        }
      }
    }
    if (changes.length === 0) { setMsg('لا توجد تغييرات للحفظ'); return; }
    setMsg(null);
    startTransition(async () => {
      const res = await fetch('/api/schedule/save', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ year: settings.year, month: settings.month, changes }),
      });
      const json = await res.json();
      if (!res.ok) { setMsg(json.error || 'فشل الحفظ'); return; }
      setMsg('✅ تم حفظ التعديلات');
      // تحديث الـ grid الأصلي بدون إعادة تحميل
      setGridOriginal(JSON.parse(JSON.stringify(grid)));
    });
  }

  function setCell(empId: string, dateISO: string, value: string) {
    setGrid((g) => ({ ...g, [empId]: { ...(g[empId] || {}), [dateISO]: value } }));
  }

  const headerDays = useMemo(() => {
    if (!settings.year || !settings.month) return [] as string[];
    const start = startOfMonth(new Date(settings.year, (settings.month || 1) - 1, 1));
    const end = endOfMonth(start);
    const days: string[] = [];
    for (let d = new Date(start); d <= end; d = addDays(d, 1)) {
      days.push(format(d, 'd'));
    }
    return days;
  }, [settings.year, settings.month]);


  return (
    <div className="space-y-6">
      {/* معلومات الجدول */}
      {data && (
        <div className="flex flex-wrap items-center gap-3 p-4 bg-slate-50 rounded-xl border border-slate-200">
          <div className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-indigo-500 to-indigo-600 rounded-lg shadow-sm">
            <span className="text-white">📅</span>
            <span className="text-base font-bold text-white">
              {getMonthName(data.month.month)} {data.month.year}
            </span>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-white rounded-lg border border-slate-200">
            <span className="text-slate-400">👥</span>
            <span className="text-sm font-medium text-slate-700">{data.employees.length} موظفة</span>
          </div>
          {data.debug && (
            <>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-yellow-50 rounded-lg border border-yellow-200">
                <span>☀️</span>
                <span className="text-sm font-medium text-yellow-700">صباح: {data.debug.coverageMorning}</span>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-indigo-50 rounded-lg border border-indigo-200">
                <span>🌙</span>
                <span className="text-sm font-medium text-indigo-700">مساء: {data.debug.coverageEvening}</span>
              </div>
            </>
          )}
          <div className="ms-auto">
            {isPreviewMode ? (
              <span className="badge badge-warning">
                <span>⏳</span>
                <span>معاينة - غير محفوظ</span>
              </span>
            ) : (
              <span className="badge badge-success">
                <span>✓</span>
                <span>محفوظ</span>
              </span>
            )}
          </div>
        </div>
      )}
      
      {/* Variation Selector */}
      {showVariationSelector && (
        <VariationSelector
          onGenerate={(strategy, offset) => {
            setShowVariationSelector(false);
            generateNewScheduleWithVariation(strategy, offset);
          }}
          isGenerating={isGenerating}
        />
      )}
      
      {/* أزرار التحكم */}
      <div className="flex gap-3 items-center flex-wrap">
        {/* زر توليد جدول الشهر التالي */}
        <button
          onClick={async () => {
            if (!settings.year || !settings.month || !data) return;
            setMsg('جاري توليد جدول الشهر التالي...');
            const nextYear = settings.month === 12 ? settings.year + 1 : settings.year;
            const nextMonth = settings.month === 12 ? 1 : settings.month + 1;
            
            // استخراج lastWeekShifts من الجدول المعروض حاليًا (آخر 7 أيام)
            const lastWeekShifts: Record<string, 'Morning' | 'Evening'> = {};
            if (data.assignments && data.assignments.length > 0) {
              // جمع كل التواريخ وترتيبها
              const allDates = Array.from(new Set(data.assignments.map(a => a.date))).sort();
              const lastWeekDates = allDates.slice(-7);
              
              for (const emp of data.employees) {
                const empId = String(emp.id); // تأكد من أنه string
                // البحث عن آخر شفت للموظفة في آخر 7 أيام
                for (let i = lastWeekDates.length - 1; i >= 0; i--) {
                  const d = lastWeekDates[i];
                  const assignment = data.assignments.find(a => String(a.employee_id) === empId && a.date === d);
                  if (!assignment) continue;
                  const symbol = (assignment.symbol || '').toUpperCase();
                  // Morning shifts: MA1, MA2, M2, PT4
                  if (symbol.startsWith('M') || symbol === 'PT4') {
                    lastWeekShifts[empId] = 'Morning';
                    break;
                  }
                  // Evening shifts: EA1, E5, E2, MA4, PT5
                  if (symbol.startsWith('E') || symbol === 'PT5' || symbol === 'MA4') {
                    lastWeekShifts[empId] = 'Evening';
                    break;
                  }
                }
              }
            }
            
            console.log('[UI] ══════════════════════════════════════════════════');
            console.log('[UI] lastWeekShifts from current grid:', Object.keys(lastWeekShifts).length, 'employees');
            console.log('[UI] ALL lastWeekShifts:', JSON.stringify(lastWeekShifts));
            console.log('[UI] ══════════════════════════════════════════════════');
            
            // عند توليد الشهر التالي، lastWeekShifts من الشهر الحالي تصبح firstWeekShifts للشهر التالي
            // لأن الأسبوع الأخير من الشهر الحالي يكمل في أول أسبوع من الشهر التالي
            const res = await fetch('/api/schedule/generate', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ 
                year: nextYear, 
                month: nextMonth, 
                firstWeekShifts: lastWeekShifts,  // شفتات آخر أسبوع من الشهر الحالي = أول أسبوع من الشهر التالي
                lastWeekShifts  // أيضًا نمرره للتوافق
              })
            });
            const json = await res.json();
            if (json && json.assignments) {
              setSettings({ year: nextYear, month: nextMonth });
              setData(json);
              updateGridFromData(json);
              setIsPreviewMode(true);
              setMsg(`✅ تم توليد جدول الشهر التالي (${getMonthName(nextMonth)} ${nextYear})`);
            } else {
              setMsg('❌ فشل في توليد الشهر التالي');
            }
          }}
          className="px-5 py-2.5 bg-gradient-to-r from-purple-500 to-purple-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg flex items-center gap-2 transition-all"
        >
          <span>⏭️</span>
          <span>توليد جدول الشهر التالي</span>
        </button>
        {/* زر توليد جدول جديد */}
        <button 
          onClick={() => setShowVariationSelector(!showVariationSelector)} 
          className="px-5 py-2.5 bg-gradient-to-r from-indigo-500 to-indigo-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg disabled:opacity-60 flex items-center gap-2 transition-all" 
          disabled={isPending || isGenerating}
        >
          {(isPending || isGenerating) ? (
            <>
              <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span>جاري التوليد...</span>
            </>
          ) : (
            <>
              <span>🔄</span>
              <span>توليد جدول جديد</span>
            </>
          )}
        </button>
        
        {/* زر حفظ الجدول */}
        <button 
          onClick={saveCurrentScheduleToDb} 
          className="px-5 py-2.5 bg-gradient-to-r from-green-500 to-green-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg disabled:opacity-60 flex items-center gap-2 transition-all" 
          disabled={isPending || isGenerating || Object.keys(grid).length === 0}
        >
          <span>💾</span>
          <span>حفظ الجدول</span>
        </button>
        
        {/* زر تحميل المحفوظ */}
        <button 
          onClick={loadSavedSchedule} 
          className="px-5 py-2.5 bg-slate-600 text-white rounded-xl font-medium hover:bg-slate-700 disabled:opacity-60 flex items-center gap-2 transition-all" 
          disabled={isPending}
        >
          <span>📂</span>
          <span>تحميل المحفوظ</span>
        </button>
        
        {/* زر حفظ التعديلات */}
        <button 
          onClick={saveChanges} 
          className="px-5 py-2.5 bg-gradient-to-r from-teal-500 to-teal-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg disabled:opacity-60 flex items-center gap-2 transition-all" 
          disabled={isPending}
        >
          <span>✏️</span>
          <span>حفظ التعديلات</span>
        </button>
        
        <div className="h-8 w-px bg-slate-200 mx-1"></div>
        
        {/* زر تصدير Excel */}
        <button 
          onClick={exportExcel} 
          className="px-5 py-2.5 bg-gradient-to-r from-emerald-500 to-emerald-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg flex items-center gap-2 transition-all"
        >
          <span>📥</span>
          <span>تصدير Excel</span>
        </button>
        
        {/* زر استيراد Excel */}
        <label className="px-5 py-2.5 bg-gradient-to-r from-sky-500 to-sky-600 text-white rounded-xl font-medium shadow-md hover:shadow-lg cursor-pointer flex items-center gap-2 transition-all">
          <span>📤</span>
          <span>{isImporting ? 'جاري الاستيراد...' : 'استيراد Excel'}</span>
          <input
            type="file"
            accept=".xlsx,.xls"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                importExcel(file);
                e.target.value = '';
              }
            }}
          />
        </label>
      </div>
      
      {/* رسالة الحالة */}
      {msg && (
        <div className={`text-sm p-4 rounded-xl flex items-center gap-3 ${
          msg.startsWith('✅') 
            ? 'bg-green-50 text-green-800 border border-green-200' 
            : msg.startsWith('❌') 
              ? 'bg-red-50 text-red-800 border border-red-200' 
              : 'bg-blue-50 text-blue-800 border border-blue-200'
        }`}>
          <span className="text-lg">{msg.startsWith('✅') ? '✅' : msg.startsWith('❌') ? '❌' : 'ℹ️'}</span>
          <span>{msg.replace(/^[✅❌]\s*/, '')}</span>
        </div>
      )}

      {!data ? (
        <div className="flex flex-col items-center justify-center py-12 text-slate-400">
          <span className="text-4xl mb-3">📊</span>
          <span className="text-sm">جاري تحميل الجدول...</span>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-slate-200 shadow-sm" dir="ltr">
          <table className="min-w-full text-xs schedule-table">
            <thead>
              <tr>
                <th className="p-3 text-left font-semibold sticky right-0 bg-slate-800 z-20">NAME</th>
                <th className="p-3 text-center font-semibold bg-slate-800">ID</th>
                {headerDays.map((d) => (
                  <th key={d} className="p-2 text-center font-medium" style={{ minWidth: 40 }}>{d}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.employees.map((emp, empIdx) => (
                <tr key={emp.id} className={empIdx % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                  <td className="p-2 whitespace-nowrap text-left font-medium text-slate-700 sticky right-0 bg-inherit border-l border-slate-200 z-10">
                    {emp.name}
                  </td>
                  <td className="p-2 text-center text-slate-500 border-l border-slate-200">{emp.code || '-'}</td>
                  {headerDays.map((dStr, idx) => {
                    const iso = toISO(data.month.year, data.month.month, Number(dStr));
                    const val = grid[String(emp.id)]?.[iso] ?? '';
                    const upper = val.toString().toUpperCase();

                    // حساب اليوم للـ week separator
                    const dayOfWeek = new Date(data.month.year, data.month.month - 1, Number(dStr)).getDay();
                    const isWeekStart = dayOfWeek === 6; // السبت
                    
                    // تلوين بحسب نوع الشفت
                    let colorClass = 'shift-cell ';
                    if (upper === 'O') {
                      colorClass += 'shift-off';
                    } else if (upper === 'V') {
                      colorClass += 'shift-vacation';
                    } else if (upper === 'B') {
                      colorClass += 'shift-between';
                    } else if (upper.startsWith('M') || upper === 'PT4') {
                      colorClass += 'shift-morning';
                    } else if (upper.startsWith('E') || upper === 'PT5') {
                      colorClass += 'shift-evening';
                    }

                    return (
                      <td key={idx} className={`p-0 text-center border-l border-slate-100 ${colorClass}`}>
                        <input
                          className="w-full text-center py-2 px-1 border-0 focus:ring-2 focus:ring-teal-500 focus:ring-inset bg-transparent font-medium text-slate-700"
                          value={val}
                          onChange={(e)=>setCell(emp.id, iso, e.target.value.toUpperCase())}
                        />
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      
      {/* Legend */}
      <div className="flex flex-wrap items-center gap-4 p-4 bg-slate-50 rounded-xl border border-slate-200 text-xs">
        <span className="font-medium text-slate-600">دليل الرموز:</span>
        <div className="flex items-center gap-1.5">
          <span className="w-6 h-6 rounded shift-morning flex items-center justify-center font-medium">M</span>
          <span className="text-slate-600">صباح</span>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="w-6 h-6 rounded shift-evening flex items-center justify-center font-medium">E</span>
          <span className="text-slate-600">مساء</span>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="w-6 h-6 rounded shift-off flex items-center justify-center font-medium">O</span>
          <span className="text-slate-600">إجازة أسبوعية</span>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="w-6 h-6 rounded shift-vacation flex items-center justify-center font-medium">V</span>
          <span className="text-slate-600">إجازة</span>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="w-6 h-6 rounded shift-between flex items-center justify-center font-medium">B</span>
          <span className="text-slate-600">Between</span>
        </div>
      </div>
    </div>
  );
}
